name: CI

on:
  push:
    branches:
      - master
    tags-ignore:
      - 'release-*'
    paths:
      - 'luci-app-device-list/**'
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build the IPK
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Prepare
      run: |
        mkdir -p bin/luci-app-device-list
        cp -rf ./luasrc ./root ./Makefile ./files ./bin/luci-app-device-list
    - name: Docker Build
      run: |
        docker pull openwrt/sdk
        docker run --rm -u root -v "$(pwd)"/bin/:/home/build/openwrt/bin -v ${{ github.workspace }}/.github/workflows:/home/build/workflows openwrt/sdk /bin/sh /home/build/workflows/build.sh
    - name: Upload app
      uses: actions/upload-artifact@v3
      with:
        name: luci-app-device-list
        path: ./bin/packages/x86_64/base/*device-list*
        if-no-files-found: error
    - name: Upload Log
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: buildlog
        path: bin/logs.tar.xz
