name: Release

on:
  push:
    tags:
      - 'release-*'

jobs:
  build:
    name: Build the IPK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Prepare
        run: |
          mkdir -p bin/luci-app-device-list
          cp -rf ./luasrc ./root ./Makefile ./files ./bin/luci-app-device-list
      - name: Docker Build
        run: |
          docker pull openwrt/sdk
          docker run --rm -u root -v "$(pwd)"/bin/:/builder/bin -v ${{ github.workspace }}/.github/workflows:/builder/workflows -v "${{ github.workspace }}/setup.sh":/builder/setup.sh openwrt/sdk /bin/sh /builder/workflows/build.sh
      - name: Install hub
        run: |
          sudo apt-get update
          sudo apt-get install -y hub
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          assets=()
          for asset in ./bin/packages/x86_64/base/*device-list*.ipk; do
            assets+=("-a" "$asset")
          done
          tag_name=$(basename ${{github.ref}})
          hub release create -p "${assets[@]}" -m "$tag_name" "$tag_name"
      - name: Upload Log
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: buildlog
          path: bin/logs.tar.xz
